services:
  apisix:
    depends_on: !reset {}
    environment:
      DATARIVER_API_UPSTREAM: ${DATARIVER_API_UPSTREAM:-host.docker.internal:8000}
    extra_hosts:
      - "host.docker.internal:host-gateway"
