from __future__ import annotations

from enum import StrEnum

MAXIMUM_CHAT_VECTOR_CANDIDATES = 20
MAXIMUM_CHAT_VECTOR_TEXT_CHARACTERS = 512


class ChatRetrievalMode(StrEnum):
    AUTO = "AUTO"
    GENERAL = "GENERAL"
    VECTOR = "VECTOR"
    GRAPH = "GRAPH"


class ChatRouteReason(StrEnum):
    EXPLICIT_SELECTION = "EXPLICIT_SELECTION"
    GRAPH_INTENT = "GRAPH_INTENT"
    SEMANTIC_INTENT = "SEMANTIC_INTENT"
    GENERAL_DEFAULT = "GENERAL_DEFAULT"


class ChatAdapterState(StrEnum):
    READY = "READY"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"


class ChatWorkflowStage(StrEnum):
    AUTHORIZATION = "AUTHORIZATION"
    BUDGET_RESERVATION = "BUDGET_RESERVATION"
    ROUTING = "ROUTING"
    RETRIEVAL = "RETRIEVAL"
    RERANKING = "RERANKING"
    COMPOSITION = "COMPOSITION"
    CITATION_VALIDATION = "CITATION_VALIDATION"
    PERSISTENCE = "PERSISTENCE"


class ChatWorkflowStatus(StrEnum):
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"
    REFUSED = "REFUSED"
